--------------------------------------------------------
--  File created - Wednesday-October-09-2013   
--------------------------------------------------------
-- Unable to render TABLE DDL for object SILVER.ENV030_LOCDETS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.ENV_F030KEY ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, OBJ_LOC ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.ENV_F030KEY_K1 ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, SEQUENCE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.ENV030_LOCDETS 
(
  OBJ_TYPE VARCHAR2(4 BYTE) 
, OBJ_LOC VARCHAR2(10 BYTE) 
, DATE_FR DATE 
, OBJ_DESC VARCHAR2(35 BYTE) 
, SEQUENCE NUMBER(6, 0) 
, LOC_TYPE VARCHAR2(4 BYTE) 
, ADD_FORM VARCHAR2(4 BYTE) 
, ADD_NAM VARCHAR2(35 BYTE) 
, ADD_NUM VARCHAR2(10 BYTE) 
, ADD_ST VARCHAR2(35 BYTE) 
, ADD_DIS VARCHAR2(35 BYTE) 
, ADD_TWN VARCHAR2(35 BYTE) 
, ADD_CTY VARCHAR2(35 BYTE) 
, ADD_CNT VARCHAR2(35 BYTE) 
, PC VARCHAR2(10 BYTE) 
, TEL_1 VARCHAR2(35 BYTE) 
, TEL_2 VARCHAR2(35 BYTE) 
, FAX_1 VARCHAR2(35 BYTE) 
, FAX_2 VARCHAR2(35 BYTE) 
, REG_ID VARCHAR2(10 BYTE) 
, NAT_ID VARCHAR2(10 BYTE) 
, NAT_CL VARCHAR2(4 BYTE) 
, NHS_PURC VARCHAR2(5 BYTE) 
, NHS_PROV VARCHAR2(5 BYTE) 
, HEAD_TYP VARCHAR2(4 BYTE) 
, HEADLOC VARCHAR2(10 BYTE) 
, CONTACT1 VARCHAR2(35 BYTE) 
, CONTACT2 VARCHAR2(35 BYTE) 
, CONTACT3 VARCHAR2(35 BYTE) 
, COMMS VARCHAR2(4 BYTE) 
, INTER VARCHAR2(35 BYTE) 
, EMAIL VARCHAR2(35 BYTE) 
, COST VARCHAR2(20 BYTE) 
, DEBTOR VARCHAR2(10 BYTE) 
, OWN_OBJT VARCHAR2(4 BYTE) 
, OWN_OBJ VARCHAR2(10 BYTE) 
, DATE_TO DATE 
, HDDR_GROUP CHAR(48 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 7340032 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.LIB003_LOOKUPCODE with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.LIB003_LOOKUPCOD_SORTE_IDX_011 ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC, DESCRIPT ASC, LDESC ASC) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 851968 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX SILVER.LIB_F003KEY ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.LIB003_LOOKUPCODE 
(
  SYS VARCHAR2(4 BYTE) 
, ULNKEY VARCHAR2(5 BYTE) 
, CODE VARCHAR2(8 BYTE) 
, DESCRIPT VARCHAR2(30 BYTE) 
, LDESC VARCHAR2(50 BYTE) 
, PARAM VARCHAR2(15 BYTE) 
, ABBREV VARCHAR2(5 BYTE) 
, FUNC NUMBER(2, 0) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.NEXT_OF_KINS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F034KEY ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, SEQ_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 9437184 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.NEXT_OF_KIN_I1 ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, NEXT_OF_KIN_RELATION ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 262144 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.NEXT_OF_KINS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, SEQ_NO NUMBER(4, 0) 
, NEXT_OF_KIN_RELATION VARCHAR2(4 BYTE) 
, REL_TEXT VARCHAR2(35 BYTE) 
, DISC_IND VARCHAR2(4 BYTE) 
, TITLE VARCHAR2(4 BYTE) 
, SURNAME VARCHAR2(35 BYTE) 
, FORENAME1 VARCHAR2(20 BYTE) 
, ADDR_FORMAT VARCHAR2(4 BYTE) 
, PROPERTY_NAME VARCHAR2(35 BYTE) 
, PROPERTY_NO VARCHAR2(10 BYTE) 
, ADDRESS_LINE_1 VARCHAR2(35 BYTE) 
, ADDRESS_LINE_2 VARCHAR2(35 BYTE) 
, ADDRESS_LINE_3 VARCHAR2(35 BYTE) 
, ADDRESS_LINE_4 VARCHAR2(35 BYTE) 
, POSTCODE VARCHAR2(9 BYTE) 
, HOME_PHONE_NO VARCHAR2(35 BYTE) 
, DAY_PHONE_NO VARCHAR2(35 BYTE) 
, DATE_START DATE 
, DATE_END DATE 
, HDDR_GROUP CHAR(48 BYTE) 
, REL_STAT VARCHAR2(4 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 9437184 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.NUMBER_IDS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.PATIENT_NO_IDX ON SILVER.NUMBER_IDS (RM_PATIENT_NO ASC, NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.PNO_IDX ON SILVER.NUMBER_IDS (NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.NUMBER_IDS 
(
  NUMBER_ID VARCHAR2(10 BYTE) 
, NUM_ID_TYPE VARCHAR2(4 BYTE) 
, RM_PATIENT_NO NUMBER(8, 0) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 92274688 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.OUT040_REFDETS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.OUT_F040KEY ON SILVER.OUT040_REFDETS (REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 14680064 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX SILVER.OUT_F040KEY_K1 ON SILVER.OUT040_REFDETS (X_CN ASC, DATEX ASC, TIMEX ASC, REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 17825792 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.REC_DT_IDX ON SILVER.OUT040_REFDETS (DT_REC ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 11534336 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.OUT040_REFDETS 
(
  REFNO NUMBER(8, 0) 
, X_CN NUMBER(8, 0) 
, DATEX DATE 
, TIMEX VARCHAR2(5 BYTE) 
, METHOD VARCHAR2(4 BYTE) 
, DT_REC DATE 
, REC_LOC VARCHAR2(10 BYTE) 
, SRCE_REF VARCHAR2(4 BYTE) 
, S_TYPE VARCHAR2(4 BYTE) 
, SOURCE VARCHAR2(10 BYTE) 
, P_TYPE VARCHAR2(4 BYTE) 
, REF_PERS VARCHAR2(10 BYTE) 
, DISCIP VARCHAR2(10 BYTE) 
, REASON VARCHAR2(4 BYTE) 
, PRIORITY VARCHAR2(4 BYTE) 
, CANCER VARCHAR2(1 BYTE) 
, CAN_TYPE VARCHAR2(2 BYTE) 
, REF VARCHAR2(17 BYTE) 
, REF_TO VARCHAR2(10 BYTE) 
, REF_SPEC VARCHAR2(10 BYTE) 
, REF_TEXT VARCHAR2(4000 BYTE) 
, CUR_LOC VARCHAR2(8 BYTE) 
, DIAGTYPE VARCHAR2(4 BYTE) 
, DIAGCODE VARCHAR2(10 BYTE) 
, DIAGTEXT VARCHAR2(4000 BYTE) 
, DT_CLOSE DATE 
, TM_CLOSE VARCHAR2(5 BYTE) 
, PC_TYPE VARCHAR2(4 BYTE) 
, CLS_PERS VARCHAR2(10 BYTE) 
, CLS_REAS VARCHAR2(8 BYTE) 
, HDDR_GROUP CHAR(48 BYTE) 
, USED_COUNT NUMBER(6, 0) 
, USRCODET VARCHAR2(4 BYTE) 
, USRCODEC_1 VARCHAR2(12 BYTE) 
, USRCODEC_2 VARCHAR2(12 BYTE) 
, USRCODEC_3 VARCHAR2(12 BYTE) 
, USRCODEC_4 VARCHAR2(12 BYTE) 
, USRCODEC_5 VARCHAR2(12 BYTE) 
, USRCODEC_6 VARCHAR2(12 BYTE) 
, USRCODEC_7 VARCHAR2(12 BYTE) 
, USRCODEC_8 VARCHAR2(12 BYTE) 
, USRCODEC_9 VARCHAR2(12 BYTE) 
, USRCODEC_10 VARCHAR2(12 BYTE) 
, REF_ORG VARCHAR2(10 BYTE) 
, RTT VARCHAR2(1 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 83886080 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.PATIENT_GPS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F033KEY ON SILVER.PATIENT_GPS (RM_PATIENT_NO ASC, DATE_FROM ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 36700160 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.CRS_F033KEY_K1 ON SILVER.PATIENT_GPS (PRACTICE_CODE ASC, DATE_FROM ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 49283072 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.PATIENT_GPS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, DATE_FROM DATE 
, GP_ID VARCHAR2(10 BYTE) 
, PRACTICE_CODE VARCHAR2(10 BYTE) 
, HDDR_GROUP CHAR(48 BYTE) 
, DATE_TO DATE 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 142606336 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.PATIENTS with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F030KEY_K1 ON SILVER.PATIENTS (DATE_OF_BIRTH ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 38797312 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX SILVER.PATIENT_KEY ON SILVER.PATIENTS (RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.PATIENTS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, FICT_CLIENT VARCHAR2(1 BYTE) 
, DISC_CLIENT VARCHAR2(1 BYTE) 
, SEX VARCHAR2(4 BYTE) 
, BIOLOGICAL_SEX VARCHAR2(4 BYTE) 
, MARITAL_STAT VARCHAR2(4 BYTE) 
, RELIGION VARCHAR2(4 BYTE) 
, DATE_OF_BIRTH DATE 
, TIME_OF_BIRTH VARCHAR2(5 BYTE) 
, PLACE_OF_BIRTH VARCHAR2(30 BYTE) 
, BIRTH_NOTIFICATION VARCHAR2(4 BYTE) 
, DATE_OF_DEATH DATE 
, TIME_OF_DEATH VARCHAR2(5 BYTE) 
, PLACE_OF_DEATH VARCHAR2(4 BYTE) 
, DEATH_NOTIFICATION VARCHAR2(4 BYTE) 
, DATE_DOD_NOTIFIED DATE 
, DATE_POST_MORTEM DATE 
, OUTCOME_PM VARCHAR2(4 BYTE) 
, DEATH_CAUSE VARCHAR2(35 BYTE) 
, BLOOD_GRP VARCHAR2(4 BYTE) 
, RHESUS VARCHAR2(4 BYTE) 
, ETHNIC_GRP VARCHAR2(4 BYTE) 
, LANGUAGE VARCHAR2(4 BYTE) 
, OLANG VARCHAR2(4 BYTE) 
, INTERPRETER_REQD VARCHAR2(4 BYTE) 
, IMM_STAT VARCHAR2(4 BYTE) 
, ENG_SPK VARCHAR2(4 BYTE) 
, STAFF_MEMBER VARCHAR2(4 BYTE) 
, EMP_CATEGORY VARCHAR2(4 BYTE) 
, OCCUPATION_CODE VARCHAR2(5 BYTE) 
, OCCUPATION_DESC VARCHAR2(35 BYTE) 
, DAY_PHONE_NO VARCHAR2(35 BYTE) 
, DATE_REGISTERED DATE 
, DATE_REG_SICK_DISABLED DATE 
, HDDR_GROUP CHAR(48 BYTE) 
, NHS_STAT VARCHAR2(2 BYTE) 
, WTEL VARCHAR2(35 BYTE) 
, MTEL VARCHAR2(35 BYTE) 
, MTEL_CS VARCHAR2(1 BYTE) 
, EMAIL VARCHAR2(50 BYTE) 
, EMAIL_CS VARCHAR2(1 BYTE) 
, PDS_FLAG VARCHAR2(1 BYTE) 
, PDS_SCN NUMBER(6, 0) 
, PDS_SYNC DATE 
, PDS_DCPL VARCHAR2(1 BYTE) 
, CTS_FLAG VARCHAR2(1 BYTE) 
, CTS_TEXT VARCHAR2(500 BYTE) 
, SMOKER VARCHAR2(4 BYTE) 
, NOTES VARCHAR2(2000 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 201326592 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.PATIENT_ADDRS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F032KEY ON SILVER.PATIENT_ADDRS (RM_PATIENT_NO ASC, ADDR_TYPE ASC, DATE_START ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 44040192 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.CRS_F032KEY_K1 ON SILVER.PATIENT_ADDRS (POSTCODE ASC, PROPERTY_NO ASC, DATE_START ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 57671680 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.PATIENT_ADDRS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, ADDR_TYPE VARCHAR2(1 BYTE) 
, DATE_START DATE 
, ADDR_FORMAT VARCHAR2(4 BYTE) 
, PROPERTY_NAME VARCHAR2(35 BYTE) 
, PROPERTY_NO VARCHAR2(10 BYTE) 
, ADDR1 VARCHAR2(35 BYTE) 
, ADDR2 VARCHAR2(35 BYTE) 
, ADDR3 VARCHAR2(35 BYTE) 
, ADDR4 VARCHAR2(35 BYTE) 
, ADDR5 VARCHAR2(35 BYTE) 
, POSTCODE VARCHAR2(9 BYTE) 
, HA_CODE VARCHAR2(4 BYTE) 
, TEL_NO VARCHAR2(35 BYTE) 
, DWELLING_TYPE VARCHAR2(4 BYTE) 
, SHARING_ACCOM VARCHAR2(4 BYTE) 
, DATE_END DATE 
, HDDR_GROUP CHAR(48 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 234881024 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.SURNAME_IDS with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PATNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.PATNO_NAME_IDX ON SILVER.SURNAME_IDS (RM_PATIENT_NO ASC, SURNAME_TYPE ASC, SURNAME_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.SOUNDEX_IDX ON SILVER.SURNAME_IDS (SURNAME_ID_SOUNDEX ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.SURNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, SURNAME_TYPE ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.SURNAME_IDS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, SURNAME_TYPE VARCHAR2(2 BYTE) 
, SURNAME_ID VARCHAR2(35 BYTE) 
, NAME1 VARCHAR2(20 BYTE) 
, NAME2 VARCHAR2(20 BYTE) 
, TITLE VARCHAR2(5 BYTE) 
, SURNAME_ID_SOUNDEX VARCHAR2(4 BYTE) 
, NAME1_SOUNDEX VARCHAR2(4 BYTE) 
, NAME2_SOUNDEX VARCHAR2(4 BYTE) 
, HDDR_GROUP CHAR(48 BYTE) 
, NAME3 VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 167772160 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.ENV_F030KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.ENV_F030KEY ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, OBJ_LOC ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.ENV_F030KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.ENV_F030KEY_K1 ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, SEQUENCE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.LIB003_LOOKUPCOD_SORTE_IDX_011 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.LIB003_LOOKUPCOD_SORTE_IDX_011 ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC, DESCRIPT ASC, LDESC ASC) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 851968 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.LIB_F003KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.LIB_F003KEY ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F034KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F034KEY ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, SEQ_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 9437184 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.NEXT_OF_KIN_I1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.NEXT_OF_KIN_I1 ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, NEXT_OF_KIN_RELATION ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 262144 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PNO_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PNO_IDX ON SILVER.NUMBER_IDS (NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATIENT_NO_IDX with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.PATIENT_NO_IDX ON SILVER.NUMBER_IDS (RM_PATIENT_NO ASC, NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.OUT_F040KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.OUT_F040KEY_K1 ON SILVER.OUT040_REFDETS (X_CN ASC, DATEX ASC, TIMEX ASC, REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 17825792 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.REC_DT_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.REC_DT_IDX ON SILVER.OUT040_REFDETS (DT_REC ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 11534336 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.OUT_F040KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.OUT_F040KEY ON SILVER.OUT040_REFDETS (REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 14680064 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F033KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F033KEY ON SILVER.PATIENT_GPS (RM_PATIENT_NO ASC, DATE_FROM ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 36700160 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F033KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F033KEY_K1 ON SILVER.PATIENT_GPS (PRACTICE_CODE ASC, DATE_FROM ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 49283072 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATIENT_KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.PATIENT_KEY ON SILVER.PATIENTS (RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F030KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F030KEY_K1 ON SILVER.PATIENTS (DATE_OF_BIRTH ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 38797312 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F032KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F032KEY ON SILVER.PATIENT_ADDRS (RM_PATIENT_NO ASC, ADDR_TYPE ASC, DATE_START ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 44040192 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F032KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F032KEY_K1 ON SILVER.PATIENT_ADDRS (POSTCODE ASC, PROPERTY_NO ASC, DATE_START ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 57671680 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATNO_NAME_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PATNO_NAME_IDX ON SILVER.SURNAME_IDS (RM_PATIENT_NO ASC, SURNAME_TYPE ASC, SURNAME_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.SURNAME_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.SURNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, SURNAME_TYPE ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATNAME_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PATNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.SOUNDEX_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.SOUNDEX_IDX ON SILVER.SURNAME_IDS (SURNAME_ID_SOUNDEX ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)























