CREATE TABLE SILVER.NUMBER_IDS 
(
  NUMBER_ID CHAR(20) 
, NUM_ID_TYPE CHAR(20)
, RM_PATIENT_NO CHAR(16) 
) 

CREATE TABLE SILVER.PATIENT_GPS 
(
  RM_PATIENT_NO CHAR(16) 
, DATE_FROM DATE 
, GP_ID CHAR(20) 
, PRACTICE_CODE CHAR(20) 
, HDDR_GROUP CHAR 
, DATE_TO DATE 
)

CREATE TABLE SILVER.PATIENTS 
(
  RM_PATIENT_NO CHAR(16)
, FICT_CLIENT CHAR(20) 
, DISC_CLIENT CHAR(20) 
, SEX CHAR(20) 
, BIOLOGICAL_SEX CHAR(20)
, MARITAL_STAT CHAR(20) 
, RELIGION CHAR(20) 
, DATE_OF_BIRTH DATE 
, TIME_OF_BIRTH CHAR(20)
, PLACE_OF_BIRTH CHAR(20) 
, BIRTH_NOTIFICATION CHAR(20) 
, DATE_OF_DEATH DATE 
, TIME_OF_DEATH CHAR(20)
, PLACE_OF_DEATH CHAR(20) 
, DEATH_NOTIFICATION CHAR(20)
, DATE_DOD_NOTIFIED DATE 
, DATE_POST_MORTEM DATE 
, OUTCOME_PM CHAR(20) 
, DEATH_CAUSE CHAR(20) 
, BLOOD_GRP CHAR(20) 
, RHESUS CHAR(20) 
, ETHNIC_GRP CHAR(20) 
, LANGUAGE CHAR(20) 
, OLANG CHAR(20) 
, INTERPRETER_REQD CHAR(20) 
, IMM_STAT CHAR(20) 
, ENG_SPK CHAR(20) 
, STAFF_MEMBER CHAR(20) 
, EMP_CATEGORY CHAR(20) 
, OCCUPATION_CODE CHAR(20) 
, OCCUPATION_DESC CHAR(20)
, DAY_PHONE_NO CHAR(20)
, DATE_REGISTERED DATE 
, DATE_REG_SICK_DISABLED DATE 
, HDDR_GROUP CHAR
, NHS_STAT CHAR(20) 
, WTEL CHAR(20) 
, MTEL CHAR(20) 
, MTEL_CS CHAR(20) 
, EMAIL CHAR(20) 
, EMAIL_CS CHAR(20) 
, PDS_FLAG CHAR(20) 
, PDS_SCN CHAR(16) 
, PDS_SYNC DATE 
, PDS_DCPL CHAR(20) 
, CTS_FLAG CHAR(20) 
, CTS_TEXT CHAR(20) 
, SMOKER CHAR(20) 
, NOTES CHAR(20)
) 

CREATE TABLE SILVER.PATIENT_ADDRS 
(
  RM_PATIENT_NO CHAR(16) 
, ADDR_TYPE CHAR(20) 
, DATE_START DATE 
, ADDR_FORMAT CHAR(20) 
, PROPERTY_NAME CHAR(20) 
, PROPERTY_NO CHAR(20) 
, ADDR1 CHAR(20) 
, ADDR2 CHAR(20) 
, ADDR3 CHAR(20) 
, ADDR4 CHAR(20) 
, ADDR5 CHAR(20) 
, POSTCODE CHAR(20) 
, HA_CODE CHAR(20) 
, TEL_NO CHAR(20) 
, DWELLING_TYPE CHAR(20) 
, SHARING_ACCOM CHAR(20) 
, DATE_END DATE 
, HDDR_GROUP CHAR 
)

CREATE TABLE SILVER.SURNAME_IDS 
(
  RM_PATIENT_NO CHAR(16) 
, SURNAME_TYPE CHAR(20) 
, SURNAME_ID CHAR(20) 
, NAME1 CHAR(20) 
, NAME2 CHAR(20)
, TITLE CHAR(20) 
, SURNAME_ID_SOUNDEX CHAR(20) 
, NAME1_SOUNDEX CHAR(20) 
, NAME2_SOUNDEX CHAR(20) 
, HDDR_GROUP CHAR 
, NAME3 CHAR(20) 
) 
