--------------------------------------------------------
--  File created - Thursday-October-31-2013   
--------------------------------------------------------
-- Unable to render TABLE DDL for object SILVER.ENV030_LOCDETS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.ENV_F030KEY ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, OBJ_LOC ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.ENV_F030KEY_K1 ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, SEQUENCE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.ENV030_LOCDETS 
(
  OBJ_TYPE VARCHAR2(4 BYTE) 
, OBJ_LOC VARCHAR2(10 BYTE) 
, DATE_FR DATE 
, OBJ_DESC VARCHAR2(35 BYTE) 
, SEQUENCE NUMBER(6, 0) 
, LOC_TYPE VARCHAR2(4 BYTE) 
, ADD_FORM VARCHAR2(4 BYTE) 
, ADD_NAM VARCHAR2(35 BYTE) 
, ADD_NUM VARCHAR2(10 BYTE) 
, ADD_ST VARCHAR2(35 BYTE) 
, ADD_DIS VARCHAR2(35 BYTE) 
, ADD_TWN VARCHAR2(35 BYTE) 
, ADD_CTY VARCHAR2(35 BYTE) 
, ADD_CNT VARCHAR2(35 BYTE) 
, PC VARCHAR2(10 BYTE) 
, TEL_1 VARCHAR2(35 BYTE) 
, TEL_2 VARCHAR2(35 BYTE) 
, FAX_1 VARCHAR2(35 BYTE) 
, FAX_2 VARCHAR2(35 BYTE) 
, REG_ID VARCHAR2(10 BYTE) 
, NAT_ID VARCHAR2(10 BYTE) 
, NAT_CL VARCHAR2(4 BYTE) 
, NHS_PURC VARCHAR2(5 BYTE) 
, NHS_PROV VARCHAR2(5 BYTE) 
, HEAD_TYP VARCHAR2(4 BYTE) 
, HEADLOC VARCHAR2(10 BYTE) 
, CONTACT1 VARCHAR2(35 BYTE) 
, CONTACT2 VARCHAR2(35 BYTE) 
, CONTACT3 VARCHAR2(35 BYTE) 
, COMMS VARCHAR2(4 BYTE) 
, INTER VARCHAR2(35 BYTE) 
, EMAIL VARCHAR2(35 BYTE) 
, COST VARCHAR2(20 BYTE) 
, DEBTOR VARCHAR2(10 BYTE) 
, OWN_OBJT VARCHAR2(4 BYTE) 
, OWN_OBJ VARCHAR2(10 BYTE) 
, DATE_TO DATE 
, HDDR_GROUP CHAR(48 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 7340032 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.ENV040_PROFDETS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.ENV_F040KEY ON SILVER.ENV040_PROFDETS (OBJ_TYPE ASC, OBJ_PROF ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 6291456 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.ENV_F040KEY_K1 ON SILVER.ENV040_PROFDETS (OBJ_TYPE ASC, SN ASC, OBJ_PROF ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 7340032 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.GP_SURG_IDX ON SILVER.ENV040_PROFDETS (OBJ_TYPE ASC, SURG ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.ENV040_PROFDETS 
(
  OBJ_TYPE VARCHAR2(4 BYTE) 
, OBJ_PROF VARCHAR2(10 BYTE) 
, DATE_FR DATE 
, SN VARCHAR2(35 BYTE) 
, FN1 VARCHAR2(20 BYTE) 
, FN2 VARCHAR2(20 BYTE) 
, TITLE VARCHAR2(5 BYTE) 
, JOB_TTL VARCHAR2(35 BYTE) 
, BLEEP VARCHAR2(10 BYTE) 
, REG_ID VARCHAR2(10 BYTE) 
, NAT_ID VARCHAR2(10 BYTE) 
, GRADE VARCHAR2(4 BYTE) 
, ADD_FORM VARCHAR2(4 BYTE) 
, ADD_NAM VARCHAR2(35 BYTE) 
, ADD_NUM VARCHAR2(10 BYTE) 
, ADD_ST VARCHAR2(35 BYTE) 
, ADD_DIS VARCHAR2(35 BYTE) 
, ADD_TWN VARCHAR2(35 BYTE) 
, ADD_CTY VARCHAR2(35 BYTE) 
, ADD_CNT VARCHAR2(35 BYTE) 
, PC VARCHAR2(10 BYTE) 
, CONTACT VARCHAR2(35 BYTE) 
, TEL_1 VARCHAR2(35 BYTE) 
, TEL_2 VARCHAR2(35 BYTE) 
, FAX_1 VARCHAR2(35 BYTE) 
, FAX_2 VARCHAR2(35 BYTE) 
, COMMS VARCHAR2(4 BYTE) 
, INTER VARCHAR2(35 BYTE) 
, EMAIL VARCHAR2(35 BYTE) 
, PERS_NO VARCHAR2(10 BYTE) 
, COST VARCHAR2(20 BYTE) 
, SURG VARCHAR2(10 BYTE) 
, C_SPEC VARCHAR2(10 BYTE) 
, DATE_TO DATE 
, HDDR_GROUP CHAR(48 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 22020096 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.LIB003_LOOKUPCODE with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.LIB003_LOOKUPCOD_SORTE_IDX_011 ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC, DESCRIPT ASC, LDESC ASC) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 851968 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX SILVER.LIB_F003KEY ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.LIB003_LOOKUPCODE 
(
  SYS VARCHAR2(4 BYTE) 
, ULNKEY VARCHAR2(5 BYTE) 
, CODE VARCHAR2(8 BYTE) 
, DESCRIPT VARCHAR2(30 BYTE) 
, LDESC VARCHAR2(50 BYTE) 
, PARAM VARCHAR2(15 BYTE) 
, ABBREV VARCHAR2(5 BYTE) 
, FUNC NUMBER(2, 0) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.NEXT_OF_KINS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F034KEY ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, SEQ_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 9437184 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.NEXT_OF_KIN_I1 ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, NEXT_OF_KIN_RELATION ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 262144 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.NEXT_OF_KINS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, SEQ_NO NUMBER(4, 0) 
, NEXT_OF_KIN_RELATION VARCHAR2(4 BYTE) 
, REL_TEXT VARCHAR2(35 BYTE) 
, DISC_IND VARCHAR2(4 BYTE) 
, TITLE VARCHAR2(4 BYTE) 
, SURNAME VARCHAR2(35 BYTE) 
, FORENAME1 VARCHAR2(20 BYTE) 
, ADDR_FORMAT VARCHAR2(4 BYTE) 
, PROPERTY_NAME VARCHAR2(35 BYTE) 
, PROPERTY_NO VARCHAR2(10 BYTE) 
, ADDRESS_LINE_1 VARCHAR2(35 BYTE) 
, ADDRESS_LINE_2 VARCHAR2(35 BYTE) 
, ADDRESS_LINE_3 VARCHAR2(35 BYTE) 
, ADDRESS_LINE_4 VARCHAR2(35 BYTE) 
, POSTCODE VARCHAR2(9 BYTE) 
, HOME_PHONE_NO VARCHAR2(35 BYTE) 
, DAY_PHONE_NO VARCHAR2(35 BYTE) 
, DATE_START DATE 
, DATE_END DATE 
, HDDR_GROUP CHAR(48 BYTE) 
, REL_STAT VARCHAR2(4 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 9437184 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.NUMBER_IDS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.PATIENT_NO_IDX ON SILVER.NUMBER_IDS (RM_PATIENT_NO ASC, NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.PNO_IDX ON SILVER.NUMBER_IDS (NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.NUMBER_IDS 
(
  NUMBER_ID VARCHAR2(10 BYTE) 
, NUM_ID_TYPE VARCHAR2(4 BYTE) 
, RM_PATIENT_NO NUMBER(8, 0) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 92274688 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.OUT040_REFDETS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.OUT_F040KEY ON SILVER.OUT040_REFDETS (REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 14680064 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX SILVER.OUT_F040KEY_K1 ON SILVER.OUT040_REFDETS (X_CN ASC, DATEX ASC, TIMEX ASC, REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 17825792 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.REC_DT_IDX ON SILVER.OUT040_REFDETS (DT_REC ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 11534336 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.OUT040_REFDETS 
(
  REFNO NUMBER(8, 0) 
, X_CN NUMBER(8, 0) 
, DATEX DATE 
, TIMEX VARCHAR2(5 BYTE) 
, METHOD VARCHAR2(4 BYTE) 
, DT_REC DATE 
, REC_LOC VARCHAR2(10 BYTE) 
, SRCE_REF VARCHAR2(4 BYTE) 
, S_TYPE VARCHAR2(4 BYTE) 
, SOURCE VARCHAR2(10 BYTE) 
, P_TYPE VARCHAR2(4 BYTE) 
, REF_PERS VARCHAR2(10 BYTE) 
, DISCIP VARCHAR2(10 BYTE) 
, REASON VARCHAR2(4 BYTE) 
, PRIORITY VARCHAR2(4 BYTE) 
, CANCER VARCHAR2(1 BYTE) 
, CAN_TYPE VARCHAR2(2 BYTE) 
, REF VARCHAR2(17 BYTE) 
, REF_TO VARCHAR2(10 BYTE) 
, REF_SPEC VARCHAR2(10 BYTE) 
, REF_TEXT VARCHAR2(4000 BYTE) 
, CUR_LOC VARCHAR2(8 BYTE) 
, DIAGTYPE VARCHAR2(4 BYTE) 
, DIAGCODE VARCHAR2(10 BYTE) 
, DIAGTEXT VARCHAR2(4000 BYTE) 
, DT_CLOSE DATE 
, TM_CLOSE VARCHAR2(5 BYTE) 
, PC_TYPE VARCHAR2(4 BYTE) 
, CLS_PERS VARCHAR2(10 BYTE) 
, CLS_REAS VARCHAR2(8 BYTE) 
, HDDR_GROUP CHAR(48 BYTE) 
, USED_COUNT NUMBER(6, 0) 
, USRCODET VARCHAR2(4 BYTE) 
, USRCODEC_1 VARCHAR2(12 BYTE) 
, USRCODEC_2 VARCHAR2(12 BYTE) 
, USRCODEC_3 VARCHAR2(12 BYTE) 
, USRCODEC_4 VARCHAR2(12 BYTE) 
, USRCODEC_5 VARCHAR2(12 BYTE) 
, USRCODEC_6 VARCHAR2(12 BYTE) 
, USRCODEC_7 VARCHAR2(12 BYTE) 
, USRCODEC_8 VARCHAR2(12 BYTE) 
, USRCODEC_9 VARCHAR2(12 BYTE) 
, USRCODEC_10 VARCHAR2(12 BYTE) 
, REF_ORG VARCHAR2(10 BYTE) 
, RTT VARCHAR2(1 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 83886080 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.PATIENT_GPS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F033KEY ON SILVER.PATIENT_GPS (RM_PATIENT_NO ASC, DATE_FROM ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 36700160 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.CRS_F033KEY_K1 ON SILVER.PATIENT_GPS (PRACTICE_CODE ASC, DATE_FROM ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 49283072 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.PATIENT_GPS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, DATE_FROM DATE 
, GP_ID VARCHAR2(10 BYTE) 
, PRACTICE_CODE VARCHAR2(10 BYTE) 
, HDDR_GROUP CHAR(48 BYTE) 
, DATE_TO DATE 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 142606336 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.PATIENTS with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F030KEY_K1 ON SILVER.PATIENTS (DATE_OF_BIRTH ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 38797312 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE UNIQUE INDEX SILVER.PATIENT_KEY ON SILVER.PATIENTS (RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.PATIENTS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, FICT_CLIENT VARCHAR2(1 BYTE) 
, DISC_CLIENT VARCHAR2(1 BYTE) 
, SEX VARCHAR2(4 BYTE) 
, BIOLOGICAL_SEX VARCHAR2(4 BYTE) 
, MARITAL_STAT VARCHAR2(4 BYTE) 
, RELIGION VARCHAR2(4 BYTE) 
, DATE_OF_BIRTH DATE 
, TIME_OF_BIRTH VARCHAR2(5 BYTE) 
, PLACE_OF_BIRTH VARCHAR2(30 BYTE) 
, BIRTH_NOTIFICATION VARCHAR2(4 BYTE) 
, DATE_OF_DEATH DATE 
, TIME_OF_DEATH VARCHAR2(5 BYTE) 
, PLACE_OF_DEATH VARCHAR2(4 BYTE) 
, DEATH_NOTIFICATION VARCHAR2(4 BYTE) 
, DATE_DOD_NOTIFIED DATE 
, DATE_POST_MORTEM DATE 
, OUTCOME_PM VARCHAR2(4 BYTE) 
, DEATH_CAUSE VARCHAR2(35 BYTE) 
, BLOOD_GRP VARCHAR2(4 BYTE) 
, RHESUS VARCHAR2(4 BYTE) 
, ETHNIC_GRP VARCHAR2(4 BYTE) 
, LANGUAGE VARCHAR2(4 BYTE) 
, OLANG VARCHAR2(4 BYTE) 
, INTERPRETER_REQD VARCHAR2(4 BYTE) 
, IMM_STAT VARCHAR2(4 BYTE) 
, ENG_SPK VARCHAR2(4 BYTE) 
, STAFF_MEMBER VARCHAR2(4 BYTE) 
, EMP_CATEGORY VARCHAR2(4 BYTE) 
, OCCUPATION_CODE VARCHAR2(5 BYTE) 
, OCCUPATION_DESC VARCHAR2(35 BYTE) 
, DAY_PHONE_NO VARCHAR2(35 BYTE) 
, DATE_REGISTERED DATE 
, DATE_REG_SICK_DISABLED DATE 
, HDDR_GROUP CHAR(48 BYTE) 
, NHS_STAT VARCHAR2(2 BYTE) 
, WTEL VARCHAR2(35 BYTE) 
, MTEL VARCHAR2(35 BYTE) 
, MTEL_CS VARCHAR2(1 BYTE) 
, EMAIL VARCHAR2(50 BYTE) 
, EMAIL_CS VARCHAR2(1 BYTE) 
, PDS_FLAG VARCHAR2(1 BYTE) 
, PDS_SCN NUMBER(6, 0) 
, PDS_SYNC DATE 
, PDS_DCPL VARCHAR2(1 BYTE) 
, CTS_FLAG VARCHAR2(1 BYTE) 
, CTS_TEXT VARCHAR2(500 BYTE) 
, SMOKER VARCHAR2(4 BYTE) 
, NOTES VARCHAR2(2000 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 201326592 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.PATIENT_ADDRS with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F032KEY ON SILVER.PATIENT_ADDRS (RM_PATIENT_NO ASC, ADDR_TYPE ASC, DATE_START ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 44040192 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.CRS_F032KEY_K1 ON SILVER.PATIENT_ADDRS (POSTCODE ASC, PROPERTY_NO ASC, DATE_START ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 57671680 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.PATIENT_ADDRS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, ADDR_TYPE VARCHAR2(1 BYTE) 
, DATE_START DATE 
, ADDR_FORMAT VARCHAR2(4 BYTE) 
, PROPERTY_NAME VARCHAR2(35 BYTE) 
, PROPERTY_NO VARCHAR2(10 BYTE) 
, ADDR1 VARCHAR2(35 BYTE) 
, ADDR2 VARCHAR2(35 BYTE) 
, ADDR3 VARCHAR2(35 BYTE) 
, ADDR4 VARCHAR2(35 BYTE) 
, ADDR5 VARCHAR2(35 BYTE) 
, POSTCODE VARCHAR2(9 BYTE) 
, HA_CODE VARCHAR2(4 BYTE) 
, TEL_NO VARCHAR2(35 BYTE) 
, DWELLING_TYPE VARCHAR2(4 BYTE) 
, SHARING_ACCOM VARCHAR2(4 BYTE) 
, DATE_END DATE 
, HDDR_GROUP CHAR(48 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 234881024 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render TABLE DDL for object SILVER.SURNAME_IDS with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PATNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.PATNO_NAME_IDX ON SILVER.SURNAME_IDS (RM_PATIENT_NO ASC, SURNAME_TYPE ASC, SURNAME_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.SOUNDEX_IDX ON SILVER.SURNAME_IDS (SURNAME_ID_SOUNDEX ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
CREATE INDEX SILVER.SURNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, SURNAME_TYPE ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)CREATE TABLE SILVER.SURNAME_IDS 
(
  RM_PATIENT_NO NUMBER(8, 0) 
, SURNAME_TYPE VARCHAR2(2 BYTE) 
, SURNAME_ID VARCHAR2(35 BYTE) 
, NAME1 VARCHAR2(20 BYTE) 
, NAME2 VARCHAR2(20 BYTE) 
, TITLE VARCHAR2(5 BYTE) 
, SURNAME_ID_SOUNDEX VARCHAR2(4 BYTE) 
, NAME1_SOUNDEX VARCHAR2(4 BYTE) 
, NAME2_SOUNDEX VARCHAR2(4 BYTE) 
, HDDR_GROUP CHAR(48 BYTE) 
, NAME3 VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 167772160 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
REM INSERTING into SILVER.ENV030_LOCDETS
SET DEFINE OFF;
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C83083',to_date('01-NOV-93','DD-MON-RR'),'THE NEW CONINGSBY SURGERY',1705,'003',null,'THE NEW CONINGSBY SURGERY','20','SILVER STREET','CONINGSBY','LINCOLNSHIRE',null,null,'LN4  4SG','01526 344544',null,null,null,null,'C83083',null,null,null,'GMP','G9512388',null,null,null,null,null,null,null,null,'PCG','5N9',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261442GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C83085',to_date('01-MAR-95','DD-MON-RR'),'JAMES STREET FAMILY PRACT',1706,'003',null,'JAMES STREET FAMILY PRACT','49','JAMES STREET','LOUTH','LINCOLNSHIRE',null,null,'LN11 0JN','01507 611122',null,null,null,null,'C83085',null,null,null,'GMP','G8513601',null,null,null,null,null,null,null,null,'PCG','5N9',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261442GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81086',to_date('01-APR-74','DD-MON-RR'),'THE SURGERY',1378,'003',null,'THE SURGERY',null,'CLIFTON ROAD','ASHBOURNE','DERBYSHIRE',null,null,'DE6  1RR','01335 300588',null,null,null,null,'C81086',null,null,null,'GMP','G3379079',null,null,null,null,null,null,null,null,'PCG','5N6',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81087',to_date('01-APR-74','DD-MON-RR'),'ASCOT MEDICAL CENTRE',1379,'003',null,'ASCOT MEDICAL CENTRE','690','OSMASTON ROAD','DERBY',null,null,null,'DE24 8GT','01332 348845',null,null,null,null,'C81087',null,null,null,'GMP','G8606576',null,null,null,null,null,null,null,null,'PCG','5N7',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81089',to_date('01-APR-74','DD-MON-RR'),'2 GOMERSALL LANE',1380,'003',null,null,'2','GOMERSALL LANE','DRONFIELD','SHEFFIELD',null,null,'S18  1RU','01246 296600',null,null,null,null,'C81089',null,null,null,'GMP','G8907411',null,null,null,null,null,null,null,null,'PCG','5N6',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81090',to_date('01-APR-74','DD-MON-RR'),'ILKESTON HEALTH CENTRE',1381,'003',null,'ILKESTON HEALTH CENTRE',null,'SOUTH STREET','ILKESTON','DERBYSHIRE',null,null,'DE7  5PZ','0115 9322968',null,null,null,null,'C81090',null,null,null,'GMP','G8411730',null,null,null,null,null,null,null,null,'PCG','5N6',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81091',to_date('01-APR-74','DD-MON-RR'),'KILLAMARSH MEDICAL PRACT',1382,'003',null,'KILLAMARSH MEDICAL PRACT','209','SHEFFIELD ROAD','KILLAMARSH','SHEFFIELD',null,null,'S21  1DX','01142510000',null,null,null,null,'C81091',null,null,null,'GMP','G8602462',null,null,null,null,null,null,null,null,'PCG','5N6',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81092',to_date('01-APR-74','DD-MON-RR'),'THE EVELYN MEDICAL CENTRE',1383,'003',null,'THE EVELYN MEDICAL CENTRE',null,'MARSH AVENUE','HOPE',null,null,null,'S33  6RJ','01433 621557',null,null,null,null,'C81092',null,null,null,'GMP','G9107913',null,null,null,null,null,null,null,null,'PCG','5N6',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81093',to_date('01-APR-74','DD-MON-RR'),'THE MEDICAL CENTRE',1384,'003',null,'THE MEDICAL CENTRE',null,'DIMPLE HEAD, CRICH','MATLOCK','DERBYSHIRE',null,null,'DE4  5BQ','01773 852035',null,null,null,null,'C81093',null,null,null,null,null,null,null,null,null,null,null,null,null,'PCG','5N6',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
Insert into SILVER.ENV030_LOCDETS (OBJ_TYPE,OBJ_LOC,DATE_FR,OBJ_DESC,SEQUENCE,LOC_TYPE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,TEL_1,TEL_2,FAX_1,FAX_2,REG_ID,NAT_ID,NAT_CL,NHS_PURC,NHS_PROV,HEAD_TYP,HEADLOC,CONTACT1,CONTACT2,CONTACT3,COMMS,INTER,EMAIL,COST,DEBTOR,OWN_OBJT,OWN_OBJ,DATE_TO,HDDR_GROUP) values ('SURG','C81094',to_date('01-APR-74','DD-MON-RR'),'CRICH MEDICAL PRACTICE',1385,'003',null,'CRICH MEDICAL PRACTICE',null,'BULLING LANE','CRICH','DERBYSHIRE',null,null,'DE4  5DX','01773 852966',null,null,null,null,'C81094',null,null,null,'GMP','G8223032',null,null,null,null,null,null,null,null,'PCG','5N6',to_date('31-DEC-99','DD-MON-RR'),'AAAA    t1  200609261441GRA     t14 201106220759');
REM INSERTING into SILVER.ENV040_PROFDETS
SET DEFINE OFF;
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170689',to_date('01-APR-74','DD-MON-RR'),'JOHN','A','P K','DR',null,null,null,'G3170689',null,null,'SHEPSHED HEALTH CENTRE',null,'FIELD STREET','SHEPSHED','LEICESTERSHIRE',null,null,'LE12 9AL',null,'01509 601201',null,null,null,null,null,null,null,null,'C82656',null,to_date('03-JUL-99','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170696',to_date('01-APR-74','DD-MON-RR'),'RIDSDILL-SMITH','R','M','DR',null,null,null,'G3170696',null,null,'THORNHILLS','732','LONDON ROAD','LARKFIELD','MAIDSTONE,KENT',null,null,'ME20 6BG',null,'0844 4773646',null,null,null,null,null,null,null,null,'G82083',null,to_date('01-SEP-96','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170713',to_date('01-APR-74','DD-MON-RR'),'FORD','C','D','DR',null,null,null,'G3170713',null,null,'WINGATE MEDICAL CENTRE','79','BIGDALE DRIVE','NORTHWOOD','KIRKBY',null,null,'L33  6YJ',null,'0151 5462958',null,null,null,null,null,null,null,null,'N83009',null,to_date('30-APR-11','DD-MON-RR'),'JEN     t1  200609251117GRA     t14 201304161205');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170737',to_date('01-APR-74','DD-MON-RR'),'MATHER','C','E','DR',null,null,null,'G3170737',null,null,'THE SURGERY',null,'RECREATION DRIVE','BILLINGE, WIGAN','LANCASHIRE',null,null,'WN5  7LY',null,'01744892205',null,null,null,null,null,null,null,null,'N83019',null,to_date('30-JUN-95','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170751',to_date('01-APR-74','DD-MON-RR'),'OGDEN','T',null,'DR',null,null,null,'G3170751',null,null,'BEDFORD HOUSE MEDICAL CTR',null,'GLEBE STREET','ASHTON-UNDER-LYNE','LANCASHIRE',null,null,'OL6  6HD',null,'0161 3306635',null,null,null,null,null,null,null,null,'P89008',null,to_date('31-MAR-05','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170768',to_date('01-APR-74','DD-MON-RR'),'SOLOMON','M',null,'DR',null,null,null,'G3170768',null,null,'THE LIMES MEDICAL CENTRE','10-12','HODGE ROAD','WALKDEN','WORSLEY, MANCHESTER',null,null,'M28  3AT',null,'01617908621',null,null,null,null,null,null,null,null,'P87017',null,to_date('31-MAR-97','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170775',to_date('01-APR-74','DD-MON-RR'),'TENNANT','B','D','DR',null,null,null,'G3170775',null,null,'GLOUCESTER HOUSE MED.CTR.','17','STATION ROAD','URMSTON','MANCHESTER',null,null,'M41  9JS',null,'0161 7487115',null,null,null,null,null,null,null,null,'P91625',null,to_date('30-JUN-99','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170782',to_date('01-APR-74','DD-MON-RR'),'WATTS','D','C','DR',null,null,null,'G3170782',null,null,'HENDFORD WING',null,'HENDFORD LODGE','74 HENDFORD','YEOVIL',null,null,'BA20 1UJ',null,'01935 474353',null,null,null,null,null,null,null,null,'L85015',null,to_date('01-SEP-91','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170854',to_date('01-APR-74','DD-MON-RR'),'SWINGLEHURST','P','J','DR',null,null,null,'G3170854',null,null,null,'5','CHERTSEY LANE','STAINES','MIDDLESEX',null,null,'TW18 3JH',null,'01784 456619',null,null,null,null,null,null,null,null,'H81079',null,to_date('01-APR-01','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
Insert into SILVER.ENV040_PROFDETS (OBJ_TYPE,OBJ_PROF,DATE_FR,SN,FN1,FN2,TITLE,JOB_TTL,BLEEP,REG_ID,NAT_ID,GRADE,ADD_FORM,ADD_NAM,ADD_NUM,ADD_ST,ADD_DIS,ADD_TWN,ADD_CTY,ADD_CNT,PC,CONTACT,TEL_1,TEL_2,FAX_1,FAX_2,COMMS,INTER,EMAIL,PERS_NO,COST,SURG,C_SPEC,DATE_TO,HDDR_GROUP) values ('GMP','G3170861',to_date('01-APR-74','DD-MON-RR'),'PEGG','J','G','DR',null,null,null,'G3170861',null,null,'COLERIDGE MEDICAL CENTRE',null,'CANAAN WAY','OTTERY ST.MARY','DEVON',null,null,'EX11 1EQ',null,'01404 814447',null,null,null,null,null,null,null,null,'L83095',null,to_date('04-DEC-94','DD-MON-RR'),'JEN     t1  200609251117TERRY   2493201306131419');
REM INSERTING into SILVER.LIB003_LOOKUPCODE
SET DEFINE OFF;
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('lib','TITLE','DAME','DAME','DAME',null,'DAME',null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('mat','AR','9','BABY ONLY','BABY ONLY',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('mat','RFS','Z','PART CASE','PART CASE',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('mat','CAB','Y','YES','YES',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('mat','CAB','N','NO','NO',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('mat','CAB','U','UNCERTAIN','UNCERTAIN',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('crs','NHSSS','B5','NOT SENT (NEW BABY)','NOT SENT (NEW BABY)',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('crs','NHSSS','B6','NO REPLY(NEW BABY)','NO REPLY(NEW BABY)',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('crs','NHSSS','B7','NOT REQUIRED(NEW BABY)','NOT REQUIRED(NEW BABY)',null,null,null);
Insert into SILVER.LIB003_LOOKUPCODE (SYS,ULNKEY,CODE,DESCRIPT,LDESC,PARAM,ABBREV,FUNC) values ('crs','NHSSS','B9','TEST NUMBER RECIEVED(NEW BABY)','TEST NUMBER RECIEVED(NEW BABY)',null,null,null);
REM INSERTING into SILVER.NEXT_OF_KINS
SET DEFINE OFF;
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163721,1,'O',null,null,null,'WILDEGO','DAVID',null,null,null,'19 Creasy Estate','Aberdour Street','London',null,'SE1  4SL','670 0805',null,to_date('28-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163723,1,'P',null,null,null,'PRAGNELL','DAVID',null,null,null,'217 Cannon Lane','Pinner','Middlesex',null,'HA5  1JA','739 2205',null,to_date('28-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163736,1,'M',null,null,null,'VICKERS','MOKTTADIL',null,null,null,'21 Park Gate','Mount Avenue','London',null,'W5   1PX',null,null,to_date('28-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163772,1,'D',null,null,null,'QUERESHI','RICHARD',null,null,null,'Flat 62, Priory Court','Priory Rd','Eastham','London','E6   1PU','0908 606 257',null,to_date('28-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163791,1,'P',null,null,null,'MARTIN','SATNAM',null,null,null,'45 Nairn Street','London',null,null,'E14  0LQ','STEVE 814894',null,to_date('28-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163794,1,'SP',null,null,null,'SINGER','EMILY',null,null,'62','PRIORS WALK',null,'CRAWLEY','WEST SUSSEX','RH10 1NY','86 5447',null,to_date('28-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163849,1,'SP',null,null,null,'PAREKH','VIDIT',null,null,'1','1 DUDLEY AVENUE','HARROW','MIDDLESEX',null,'HA3  8ST','952 5187',null,to_date('29-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163855,1,'D',null,null,null,'LOUDOUN','SYLVIA',null,null,'13','ST FRANCIS HOUSE','BRIDGEWAY STREET','LONDON',null,'NW1  1QT','0438 729222','HITCHIN 32181',to_date('29-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140232                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163887,1,'SP',null,null,null,'ROGERS','BRIAN',null,null,null,'31 West Oak','The Avenue','Beckenham','Kent','BR3  5EZ',null,null,to_date('29-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140233                        ','NOK');
Insert into SILVER.NEXT_OF_KINS (RM_PATIENT_NO,SEQ_NO,NEXT_OF_KIN_RELATION,REL_TEXT,DISC_IND,TITLE,SURNAME,FORENAME1,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,ADDRESS_LINE_4,POSTCODE,HOME_PHONE_NO,DAY_PHONE_NO,DATE_START,DATE_END,HDDR_GROUP,REL_STAT) values (163919,1,'SP',null,null,null,'REID','ZARA',null,null,'14','SOMERSET ROAD','Southall','Middlesex',null,'UB1  2TP','0252 315138',null,to_date('30-MAR-84','DD-MON-RR'),null,'Old PAS t33 200704140233                        ','NOK');
REM INSERTING into SILVER.NUMBER_IDS
SET DEFINE OFF;
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('707609','ALN',707609);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('010612','0',10612);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('10612','ALN',10612);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('B68813','ALN',10612);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('X90263','ALN',10853);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('6360762749','NHS',10853);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('010861','0',10861);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('010613','0',10613);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('10613','ALN',10613);
Insert into SILVER.NUMBER_IDS (NUMBER_ID,NUM_ID_TYPE,RM_PATIENT_NO) values ('S90240','ALN',10613);
REM INSERTING into SILVER.OUT040_REFDETS
SET DEFINE OFF;
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1214350,708808,to_date('26-MAY-05','DD-MON-RR'),'00:01','W',to_date('31-MAY-05','DD-MON-RR'),'BC','03','SURG','E84008','GMP','G3356474',null,'A','R',null,null,null,'BEAM','PC',null,null,null,null,null,to_date('14-NOV-06','DD-MON-RR'),'00:01','CO','BEAM','TC','Old PAS t33 200706010236                        ',1,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1214351,708999,to_date('05-JAN-05','DD-MON-RR'),'00:01','W',to_date('05-JAN-05','DD-MON-RR'),'BC','11',null,null,null,null,null,'A','R',null,null,null,null,'SS',null,null,null,null,null,to_date('31-JUL-06','DD-MON-RR'),'00:01','CO',null,'TC','Old PAS t33 200706010237                        ',1,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1176781,1347576,to_date('19-DEC-06','DD-MON-RR'),'00:01','W',to_date('27-DEC-06','DD-MON-RR'),'BC','03','SURG','F85008','GMP','G8400770',null,'A','R',null,null,null,'DANR','PC',null,null,null,null,null,to_date('08-FEB-07','DD-MON-RR'),'00:01','CO','DANR','TC','Old PAS t33 200705300127                        ',0,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1176782,1347609,to_date('11-DEC-06','DD-MON-RR'),'00:01','W',to_date('13-DEC-06','DD-MON-RR'),'BC','03','SURG','F84047','GMP','G9007415',null,'A','R',null,null,null,'VERS','PC',null,null,null,null,null,to_date('06-FEB-07','DD-MON-RR'),'00:01','CO','VERS','TC','Old PAS t33 200705300127                        ',0,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1176783,1347700,to_date('29-DEC-06','DD-MON-RR'),'00:01','W',to_date('29-DEC-06','DD-MON-RR'),'BC','03','SURG',null,'GMP','G9999981',null,'A','R',null,null,null,'DAVA','PC',null,null,null,null,null,to_date('20-FEB-07','DD-MON-RR'),'00:01','CO','DAVA','TC','Old PAS t33 200705300127                        ',0,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1214352,709285,to_date('14-JUN-04','DD-MON-RR'),'00:01','W',to_date('18-JUN-04','DD-MON-RR'),'BC','15','OPPR',null,'OPMT','1',null,'A','R',null,null,null,'CUNC','CA',null,null,null,null,null,to_date('31-JUL-06','DD-MON-RR'),'00:01','CO','CUNC','TC','Old PAS t33 200706010238                        ',1,null,null,null,null,null,null,null,null,null,null,null,'NK',null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1214353,709339,to_date('23-SEP-05','DD-MON-RR'),'00:01','W',to_date('28-SEP-05','DD-MON-RR'),'BC','03','SURG','E84057','GMP','G9600674',null,'A','R',null,null,null,'BEAM','PC',null,null,null,null,null,to_date('14-MAR-07','DD-MON-RR'),'00:01','CO','BEAM','TC','Old PAS t33 200706010238                        ',1,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1176784,1347704,to_date('21-DEC-06','DD-MON-RR'),'00:01','W',to_date('29-DEC-06','DD-MON-RR'),'BC','03','SURG','G85677','GMP','G9802232',null,'A','R',null,null,null,'THOG','PC',null,null,null,null,null,to_date('19-FEB-07','DD-MON-RR'),'00:01','CO','THOG','TC','Old PAS t33 200705300127                        ',0,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1176788,1347959,to_date('03-JAN-07','DD-MON-RR'),'00:01','W',to_date('08-JAN-07','DD-MON-RR'),'BC','03','SURG','V81999','GMP','G9999981',null,'A','R',null,null,null,'MOOT','SP',null,null,null,null,null,to_date('02-MAR-07','DD-MON-RR'),'00:01','CO','MOOT','TC','Old PAS t33 200705300127                        ',0,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.OUT040_REFDETS (REFNO,X_CN,DATEX,TIMEX,METHOD,DT_REC,REC_LOC,SRCE_REF,S_TYPE,SOURCE,P_TYPE,REF_PERS,DISCIP,REASON,PRIORITY,CANCER,CAN_TYPE,REF,REF_TO,REF_SPEC,REF_TEXT,CUR_LOC,DIAGTYPE,DIAGCODE,DIAGTEXT,DT_CLOSE,TM_CLOSE,PC_TYPE,CLS_PERS,CLS_REAS,HDDR_GROUP,USED_COUNT,USRCODET,USRCODEC_1,USRCODEC_2,USRCODEC_3,USRCODEC_4,USRCODEC_5,USRCODEC_6,USRCODEC_7,USRCODEC_8,USRCODEC_9,USRCODEC_10,REF_ORG,RTT) values (1214354,709408,to_date('10-JUN-05','DD-MON-RR'),'00:01','W',to_date('10-JUN-05','DD-MON-RR'),'BC','11',null,null,null,null,null,'A','R',null,null,null,'GARD','SS',null,null,null,null,null,to_date('26-SEP-06','DD-MON-RR'),'00:01','CO','GARD','TC','Old PAS t33 200706010238                        ',1,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into SILVER.PATIENT_GPS
SET DEFINE OFF;
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (1041857,to_date('22-OCT-02','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011540                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (66820,to_date('16-JUL-82','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011540                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (13202,to_date('16-JUL-82','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011519                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (66821,to_date('16-JUL-82','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011540                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (895490,to_date('05-FEB-00','DD-MON-RR'),'G3425327','H81034','Old PAS t33 200705041143                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (66822,to_date('16-JUL-82','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011540                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (66823,to_date('16-JUL-82','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011540                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (1041858,to_date('24-SEP-02','DD-MON-RR'),'G3274851','F85068','Old PAS t33 200705011540                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (13203,to_date('16-JUL-82','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011519                        ',null);
Insert into SILVER.PATIENT_GPS (RM_PATIENT_NO,DATE_FROM,GP_ID,PRACTICE_CODE,HDDR_GROUP,DATE_TO) values (66825,to_date('16-JUL-82','DD-MON-RR'),'G9999981','V81999','Old PAS t33 200705011540                        ',null);
REM INSERTING into SILVER.PATIENTS
SET DEFINE OFF;
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (706698,null,null,'M',null,'U',null,to_date('15-APR-45','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'Z',null,null,null,null,null,null,null,null,null,null,to_date('05-JUN-96','DD-MON-RR'),null,'Old PAS t33 200704131757                        ','01',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (72428,null,null,'M',null,'U',null,to_date('11-AUG-13','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'C',null,null,null,null,null,null,null,null,null,'07113307301',to_date('16-JUL-82','DD-MON-RR'),null,'Old PAS t33 200704132128FLAD01  t992200711271638','07',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (9744,null,null,'M',null,'U',null,to_date('11-JUN-15','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'P',null,null,null,null,null,null,null,null,null,null,to_date('16-JUL-82','DD-MON-RR'),null,'Old PAS t33 200704131757FLAD01  t992200711271638','07',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (72429,null,null,'F',null,'U',null,to_date('18-AUG-16','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'Z',null,null,null,null,null,null,null,null,null,'07919101379',to_date('16-JUL-82','DD-MON-RR'),null,'Old PAS t33 200704132128FLAD01  t992200711271638','07',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (706699,null,null,'M',null,'U',null,to_date('13-APR-24','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'Z',null,null,null,null,null,null,null,null,null,null,to_date('05-JUN-96','DD-MON-RR'),null,'Old PAS t33 200704131757                        ','01',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (72430,null,null,'F',null,'U',null,to_date('23-JUN-22','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'Z',null,null,null,null,null,null,null,null,null,null,to_date('16-JUL-82','DD-MON-RR'),null,'Old PAS t33 200704132128FLAD01  t992200711271638','03',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (706700,null,null,'F',null,'U',null,to_date('03-MAY-07','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'Z',null,null,null,null,null,null,null,null,null,null,to_date('05-JUN-96','DD-MON-RR'),null,'Old PAS t33 200704131757                        ','01',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (72431,null,null,'M',null,'U',null,to_date('03-JUN-31','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,to_date('16-JUL-82','DD-MON-RR'),null,'Old PAS t33 200704132128FLAD01  t992200711271638','03',null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (9745,null,null,'F',null,'U',null,to_date('13-MAY-28','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null,null,null,null,null,null,null,null,null,to_date('16-JUL-82','DD-MON-RR'),null,'Old PAS t33 200704131757FLAD01  t992200711271638','03',null,'07799 971333',null,null,null,null,null,null,null,null,null,null,null);
Insert into SILVER.PATIENTS (RM_PATIENT_NO,FICT_CLIENT,DISC_CLIENT,SEX,BIOLOGICAL_SEX,MARITAL_STAT,RELIGION,DATE_OF_BIRTH,TIME_OF_BIRTH,PLACE_OF_BIRTH,BIRTH_NOTIFICATION,DATE_OF_DEATH,TIME_OF_DEATH,PLACE_OF_DEATH,DEATH_NOTIFICATION,DATE_DOD_NOTIFIED,DATE_POST_MORTEM,OUTCOME_PM,DEATH_CAUSE,BLOOD_GRP,RHESUS,ETHNIC_GRP,LANGUAGE,OLANG,INTERPRETER_REQD,IMM_STAT,ENG_SPK,STAFF_MEMBER,EMP_CATEGORY,OCCUPATION_CODE,OCCUPATION_DESC,DAY_PHONE_NO,DATE_REGISTERED,DATE_REG_SICK_DISABLED,HDDR_GROUP,NHS_STAT,WTEL,MTEL,MTEL_CS,EMAIL,EMAIL_CS,PDS_FLAG,PDS_SCN,PDS_SYNC,PDS_DCPL,CTS_FLAG,CTS_TEXT,SMOKER,NOTES) values (72432,null,null,'F',null,'U',null,to_date('19-AUG-03','DD-MON-RR'),null,null,null,null,null,null,null,null,null,null,null,null,null,'Z',null,null,null,null,null,null,null,null,null,null,to_date('16-JUL-82','DD-MON-RR'),null,'Old PAS t33 200704132128FLAD01  t992200711271638','07',null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into SILVER.PATIENT_ADDRS
SET DEFINE OFF;
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (8135,'H',to_date('16-JUL-82','DD-MON-RR'),null,null,'30','WOODBOURNE AVENUE','LONDON','SW16',null,null,'SW16 1UU','Q36','030 0999 0703',null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (8136,'H',to_date('16-JUL-82','DD-MON-RR'),null,null,'91','ROSEBERY AVENUE',null,'LONDON',null,null,'E12  6PT','Q36','03001090930',null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (8137,'H',to_date('16-JUL-82','DD-MON-RR'),null,null,'43','LANSDOWNE ROAD',null,'STANMORE','MIDDLESEX',null,'HA7  2RZ','Q36','07919 003 991',null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (8138,'H',to_date('05-JUL-90','DD-MON-RR'),null,null,'82','GLADSTONE PARK GARDENS',null,'LONDON',null,null,'NW2  6JX','Q36','07709 903113',null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (8139,'H',to_date('16-JUL-82','DD-MON-RR'),null,null,'57','CHAUCER ROAD',null,'LONDON',null,null,'E7   9LZ','Q36','030 0113 0719',null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (8140,'H',to_date('16-JUL-82','DD-MON-RR'),null,null,'10','SOUTH ROAD',null,'LONDON',null,null,'SW19 1UT','Q36',null,null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (1485,'H',to_date('25-MAY-82','DD-MON-RR'),null,null,'5A','5A WALLACE ROAD',null,'LONDON',null,null,'N1   2PG','Q36','07710313999',null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (1486,'H',to_date('25-MAY-82','DD-MON-RR'),null,null,'20','20 LARCHBANK','LIVINSTON',null,null,null,' ',null,null,null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (1821,'H',to_date('08-JUL-82','DD-MON-RR'),null,null,'51','THE SEASONS','SEPTEMBER WAY','STANMORE','MIDDLESEX',null,'HA7  2SE','Q36','0300 730 7139',null,null,null,'MKmigration 201310010728                        ');
Insert into SILVER.PATIENT_ADDRS (RM_PATIENT_NO,ADDR_TYPE,DATE_START,ADDR_FORMAT,PROPERTY_NAME,PROPERTY_NO,ADDR1,ADDR2,ADDR3,ADDR4,ADDR5,POSTCODE,HA_CODE,TEL_NO,DWELLING_TYPE,SHARING_ACCOM,DATE_END,HDDR_GROUP) values (1823,'H',to_date('08-JUL-82','DD-MON-RR'),null,null,'6','6 BERESFORD AVENUE, BEVERLEY ROAD',null,'HULL',null,null,'HU6  7LR','Q32','01703 777139',null,null,null,'MKmigration 201310010728                        ');
REM INSERTING into SILVER.SURNAME_IDS
SET DEFINE OFF;
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (474616,'NO','STRIDE','WENDY',null,'MRS','S363','W530',null,'Old PAS t33 200704180727                        ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (1000440,'NO','GREWAL','LINA',null,'MRS','G640','L500',null,'Old PAS t33 200704180727                        ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (474617,'NO','COLVIN','DEBBIE',null,'MISS','C415','D100',null,'Old PAS t33 200704180727                        ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (474617,'SB','COLVIN','DEBBIE',null,'MISS','C415','D100',null,'Migration001  200704180727                      ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (1000441,'NO','SANTOS','ANGELA',null,'MRS','S532','A524',null,'Old PAS t33 200704180727                        ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (1000441,'SB','SANTOS','ANGELA',null,'MRS','S532','A524',null,'Migration001  200704180727                      ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (474618,'NO','SANSOM','ROSALIND',null,'MRS','S525','R245',null,'Old PAS t33 200704180727                        ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (1000442,'NO','LASISI','HAROLDINE',null,'MISS','L220','H643',null,'Old PAS t33 200704180727                        ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (1000443,'NO','HAZAI','NARAIN',null,'MR','H200','N650',null,'Old PAS t33 200704180727                        ',null);
Insert into SILVER.SURNAME_IDS (RM_PATIENT_NO,SURNAME_TYPE,SURNAME_ID,NAME1,NAME2,TITLE,SURNAME_ID_SOUNDEX,NAME1_SOUNDEX,NAME2_SOUNDEX,HDDR_GROUP,NAME3) values (474620,'NO','FORNWALT','KHULTHUM',null,'MISS','F654','K435',null,'Old PAS t33 200704180727                        ',null);
-- Unable to render INDEX DDL for object SILVER.ENV_F030KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.ENV_F030KEY ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, OBJ_LOC ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.ENV_F030KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.ENV_F030KEY_K1 ON SILVER.ENV030_LOCDETS (OBJ_TYPE ASC, SEQUENCE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.GP_SURG_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.GP_SURG_IDX ON SILVER.ENV040_PROFDETS (OBJ_TYPE ASC, SURG ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.ENV_F040KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.ENV_F040KEY ON SILVER.ENV040_PROFDETS (OBJ_TYPE ASC, OBJ_PROF ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 6291456 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.ENV_F040KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.ENV_F040KEY_K1 ON SILVER.ENV040_PROFDETS (OBJ_TYPE ASC, SN ASC, OBJ_PROF ASC, DATE_FR ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 7340032 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.LIB003_LOOKUPCOD_SORTE_IDX_011 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.LIB003_LOOKUPCOD_SORTE_IDX_011 ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC, DESCRIPT ASC, LDESC ASC) 
LOGGING 
TABLESPACE "PCS_DATA" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 851968 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.LIB_F003KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.LIB_F003KEY ON SILVER.LIB003_LOOKUPCODE (SYS ASC, ULNKEY ASC, CODE ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 2097152 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F034KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F034KEY ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, SEQ_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 9437184 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.NEXT_OF_KIN_I1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.NEXT_OF_KIN_I1 ON SILVER.NEXT_OF_KINS (RM_PATIENT_NO ASC, NEXT_OF_KIN_RELATION ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 262144 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PNO_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PNO_IDX ON SILVER.NUMBER_IDS (NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATIENT_NO_IDX with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.PATIENT_NO_IDX ON SILVER.NUMBER_IDS (RM_PATIENT_NO ASC, NUM_ID_TYPE ASC, NUMBER_ID ASC) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.OUT_F040KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.OUT_F040KEY_K1 ON SILVER.OUT040_REFDETS (X_CN ASC, DATEX ASC, TIMEX ASC, REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 17825792 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.REC_DT_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.REC_DT_IDX ON SILVER.OUT040_REFDETS (DT_REC ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 11534336 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.OUT_F040KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.OUT_F040KEY ON SILVER.OUT040_REFDETS (REFNO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 14680064 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F033KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F033KEY ON SILVER.PATIENT_GPS (RM_PATIENT_NO ASC, DATE_FROM ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 36700160 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F033KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F033KEY_K1 ON SILVER.PATIENT_GPS (PRACTICE_CODE ASC, DATE_FROM ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 49283072 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATIENT_KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.PATIENT_KEY ON SILVER.PATIENTS (RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F030KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F030KEY_K1 ON SILVER.PATIENTS (DATE_OF_BIRTH ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 38797312 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F032KEY with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SILVER.CRS_F032KEY ON SILVER.PATIENT_ADDRS (RM_PATIENT_NO ASC, ADDR_TYPE ASC, DATE_START ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 44040192 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.CRS_F032KEY_K1 with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.CRS_F032KEY_K1 ON SILVER.PATIENT_ADDRS (POSTCODE ASC, PROPERTY_NO ASC, DATE_START ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 57671680 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATNO_NAME_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PATNO_NAME_IDX ON SILVER.SURNAME_IDS (RM_PATIENT_NO ASC, SURNAME_TYPE ASC, SURNAME_ID ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.SURNAME_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.SURNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, SURNAME_TYPE ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.PATNAME_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.PATNAME_IDX ON SILVER.SURNAME_IDS (SURNAME_ID ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
-- Unable to render INDEX DDL for object SILVER.SOUNDEX_IDX with DBMS_METADATA attempting internal generator.
CREATE INDEX SILVER.SOUNDEX_IDX ON SILVER.SURNAME_IDS (SURNAME_ID_SOUNDEX ASC, NAME1 ASC, NAME2 ASC, NAME1_SOUNDEX ASC, NAME2_SOUNDEX ASC, RM_PATIENT_NO ASC) 
LOGGING 
TABLESPACE "PCS_INDEXES" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
)
